#Se hiso modificaciones despues de agregar el contenido a mi msvc-config/configurations
spring:
  application:
    name: msvc-course
  config:
    import: optional:configserver:http://localhost:8888 #Agregado, ya que el msvc-config no esta configurado


